#!/usr/bin/env python3
import sys
import os
import argparse
import threading
from pathlib import Path

# Add src/ to python path so we can import drdo_anc modules
src_dir = Path(__file__).resolve().parent.parent / "src"
sys.path.insert(0, os.fspath(src_dir))

from drdo_anc.gui.app import run_gui
from drdo_anc.gui.bridge import GUIBridge

from drdo_anc.audio.live import (
    StreamingPipeline,
    close_sounddevice_io,
    format_device_listing,
    open_sounddevice_io,
)
DEFAULT_MODEL_NAME = "DeepFilterNet3"
DEFAULT_READ_CHUNK_SIZE = 1024

def _parse_device(value: str | None) -> int | str | None:
    if value is None:
        return None
    try:
        return int(value)
    except ValueError:
        return value

def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="DRDO-ANC Real-Time GUI")
    parser.add_argument("--list-devices", action="store_true", help="List host audio devices and exit.")
    parser.add_argument("--model", default=DEFAULT_MODEL_NAME, help="Registered enhancer model name.")
    parser.add_argument("--passthrough", action="store_true", help="Copy microphone input directly to the speaker.")
    parser.add_argument("--sample-rate", type=int, default=None, help="Audio sample rate in Hz.")
    parser.add_argument("--chunk-size", type=int, default=DEFAULT_READ_CHUNK_SIZE, help="Samples requested per AudioInput.read() call.")
    parser.add_argument("--input-device", default=None, help="Input device index or name.")
    parser.add_argument("--output-device", default=None, help="Output device index or name.")
    parser.add_argument("--fake", action="store_true", help="Run the GUI with fake animated data without accessing microphone.")
    return parser

def main() -> None:
    # Use parse_known_args so Qt can consume any standard Qt args later
    parser = _build_parser()
    args, unknown_args = parser.parse_known_args()

    if args.list_devices:
        print(format_device_listing())
        return

    bridge = GUIBridge()

    if args.fake:
        print("Starting DRDO-ANC Real-Time GUI (Fake Data Mode)...")
        # Ensure fake data is generated by NOT setting is_live to True and NOT providing a pipeline.
        run_gui(bridge=bridge)
        return

    # Real Audio Setup
    if args.passthrough:
        sample_rate = args.sample_rate or 48_000
        enhancer = None
        mode_label = "pass-through"
        model_name = "Pass-Through"
    else:
        from drdo_anc.enhancement import create_enhancer, get_model_config
        model_config = get_model_config(args.model)
        enhancer = create_enhancer(args.model)
        sample_rate = args.sample_rate or enhancer.sample_rate()
        mode_label = args.model
        model_name = args.model

    if sample_rate <= 0:
        raise SystemExit("--sample-rate must be positive.")

    input_device = _parse_device(args.input_device)
    output_device = _parse_device(args.output_device)

    print("=" * 70)
    print("DRDO-ANC | Live GUI Streaming")
    print("=" * 70)
    print(f"Mode:        {mode_label}")
    print(f"Sample rate: {sample_rate} Hz")
    print(f"Chunk size:  {args.chunk_size} samples/read")

    audio_input, audio_output = open_sounddevice_io(
        sample_rate,
        input_device=input_device,
        output_device=output_device,
        blocksize=args.chunk_size,
    )

    # Initialize Telemetry fields before starting
    bridge._latest_telemetry.model_name = model_name
    bridge._latest_telemetry.sample_rate = sample_rate

    def on_telemetry(in_chunk, out_chunk, proc_time):
        stats = getattr(audio_input, "stats", None)
        stats_dict = stats.as_dict() if stats is not None else {}
        bridge.publish_data(in_chunk, out_chunk, proc_time, stats=stats_dict)

    pipeline = StreamingPipeline(
        audio_input,
        audio_output,
        enhancer,
        read_chunk_size=args.chunk_size,
        passthrough=args.passthrough,
        telemetry_callback=on_telemetry,
    )

    def run_audio_thread():
        print("Audio thread starting...")
        try:
            pipeline.run()
        finally:
            close_sounddevice_io(audio_input, audio_output)
            print("Audio thread stopped.")

    audio_thread = threading.Thread(target=run_audio_thread, daemon=True)
    audio_thread.start()

    print("Starting PySide6 GUI...")
    try:
        run_gui(bridge=bridge)
    finally:
        print("GUI closed. Stopping audio stream...")
        pipeline.request_stop()
        audio_thread.join(timeout=2.0)

if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(0)
